In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/Users/kanchanjot/Desktop/datasets/data1.csv')
label = pd.read_csv('/Users/kanchanjot/Desktop/datasets/label1.csv') 

In [3]:
label # label is divided into classes

3
0      2
1      2
2      3
3      3
4      3
...   ..
19994  3
19995  1
19996  2
19997  2
19998  0

[19999 rows x 1 columns]

In [4]:
data

-0.4468911094795388  -0.01339702165138184  0.23264493204847725  \
0                 0.243747             -1.144175            -0.622214   
1                -1.417799             -0.088833            -0.647181   
2                 0.656784              0.381201            -1.039011   
3                 1.098520              1.706769            -1.030370   
4                -0.035569              1.481734             1.693223   
...                    ...                   ...                  ...   
19994             0.146324             -0.618555             0.547413   
19995            -2.227923             -0.327196             1.258849   
19996            -0.800405              1.477997             0.090057   
19997            -1.217344             -0.785401            -0.413781   
19998             1.601005             -0.890398            -1.425049   

       2.1566488376889117  1.6529232891493573  -0.21053079266527167  \
0               -0.661979           -0.373315              0.520313   
1               -1.141497           -1.321100              0.686798   
2                1.285315            0.808324              1.428519   
3                2.001009            2.751551              1.202229   
4                1.437399            0.822527             -1.344757   
...                   ...                 ...                   ...   
19994            0.851301            0.838880             -1.248402   
19995           -0.945254            3.925262              0.316686   
19996           -0.973997           -0.204970              0.224539   
19997           -0.335324            0.181671             -1.685733   
19998            0.887501            0.167205             -0.395042   

       -0.6622270851236525  0.7051439522485349  1.4346837198721623  \
0                -1.307954            1.639481           -2.838816   
1                -1.045569           -0.376153           -2.272447   
2                -1.144367           -0.609958            0.983676   
3                -0.941066            1.965282            2.979131   
4                -2.833138           -0.066823            0.440819   
...                    ...                 ...                 ...   
19994             0.698199           -0.545033            0.994348   
19995            -1.061159            1.846706            3.692157   
19996             0.302265            0.361146           -1.906636   
19997            -0.437981           -1.176626           -1.434436   
19998            -0.512554            0.050777           -0.034945   

       -0.4457503016296182  -0.178501071015899  -0.9055033666934242  \
0                 0.331636            0.100261            -1.173067   
1                -0.669733           -1.070732             1.091993   
2                 0.060917            0.471647            -0.594279   
3                 1.402483           -1.432987             0.400322   
4                -2.746223            0.396444             0.584890   
...                    ...                 ...                  ...   
19994            -0.054620            0.581239            -1.842074   
19995             0.698035           -0.184239            -0.546036   
19996             1.381875            0.034366             1.690199   
19997            -0.880986            2.117703            -2.136842   
19998            -0.289219            0.639189             0.981751   

       -0.5940992077798437  -0.7285856024160755  -0.6270024414706785  \
0                -0.079774             2.194899             0.242839   
1                 0.692293             0.937617             0.262142   
2                 2.104027            -1.113597            -0.188799   
3                -0.839851            -1.580974            -0.659587   
4                 0.529624            -1.389421             0.441056   
...                    ...                  ...                  ...   
19994            -0.552879            -0.102096             0.307538   
19995  

In [5]:
data = data.values
label = label.values

In [6]:
print(data.shape , label.shape)

(19999, 20) (19999, 1)


In [7]:
np.unique(label)

array([0, 1, 2, 3, 4])

In [8]:
vec_len = np.max(label) + 1

In [9]:
vec_len

5

In [10]:
onehot_labels = np.eye(vec_len)[label]

In [11]:
onehot_labels.shape

(19999, 1, 5)

In [12]:
onehot_labels

array([[[0., 0., 1., 0., 0.]],

       [[0., 0., 1., 0., 0.]],

       [[0., 0., 0., 1., 0.]],

       ...,

       [[0., 0., 1., 0., 0.]],

       [[0., 0., 1., 0., 0.]],

       [[1., 0., 0., 0., 0.]]])

In [13]:
onehot_labels = onehot_labels.reshape(19999,5)

In [14]:
onehot_labels

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [15]:
onehot_labels.shape

(19999, 5)

In [16]:
split = 0.8


trainData = data[: int(split * data.shape[0]), :]
trainlabel = onehot_labels[: int(split * data.shape[0]), :]

rem_data = data[int(split * data.shape[0]):, :]
rem_label = onehot_labels[int(split * data.shape[0]):, :]


In [17]:
print(trainData.shape , trainlabel.shape , rem_data.shape, rem_label.shape)

(15999, 20) (15999, 5) (4000, 20) (4000, 5)


In [18]:
testData = rem_data[: int(0.5 * rem_data.shape[0]), :]
testlabel = rem_label[: int(0.5 * rem_label.shape[0]), :]
validData = rem_data[int(0.5 * rem_data.shape[0]):, :]
validlabel = rem_label[int(0.5 * rem_label.shape[0]):, :]

In [19]:
print(testData.shape ,validData.shape , testlabel.shape,  validlabel.shape)

(2000, 20) (2000, 20) (2000, 5) (2000, 5)


In [20]:
hidden_neuron = 12

In [21]:
b1 = np.zeros(hidden_neuron)
b2 = np.zeros(5)

print(b1, b2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]


In [22]:
w1 = np.random.normal(0,1,(20,12))
w2 = np.random.normal(0,1, (hidden_neuron,5))

In [23]:
def activation(data, choice):
    if choice == 0:
        return np.tanh(data)
    else:
        numerator = np.exp(data)
        return numerator/np.sum(numerator , axis=1 , keepdims=True)
        

In [24]:
alpha = 0.03

In [25]:
batch = 500

In [26]:
def cost_func(pred , label):
    return -(label * np.log(pred) + (1-label) * np.log(1- pred))

In [27]:
def forward_prop(data):
    a0 = data 
    z1 = np.dot(a0, w1) + b1 
    a1 = activation(z1, 0)
    z2 = np.dot(a1,w2) + b2
    a2 = activation(z2 , 1)
    return a0 , z1 , a1 , z2, a2

In [28]:
def accuracy(pred, label, size):
    max_num = np.argmax(pred, axis=1)
    max_label = np.argmax(label , axis=1)
    compare  = np.equal(max_data ,max_label)

    return (np.sum(compare)/size)*100
    

In [29]:
epochs = 100 

In [30]:
for epoch in range(epochs):

    for num_batch in range(int(trainData.shape[0]/batch)):
        a0 , z1 , a1 , z2, a2 = forward_prop(trainData[num_batch * batch: (num_batch + 1)*batch, :])
        pred = a2
        label_batch = trainlabel[num_batch * batch: (num_batch + 1) * batch, :]
        del2 = (pred - label_batch)
        del1 = np.dot(del2,w2.T)*(1 - a1**2)
        dcdw2 = np.dot(a1.T,del2)
        dcdw1 = np.dot(a0.T , del1)
        dcdb1 = np.sum(del1 ,axis=0)
        dcdb2 = np.sum(del2 , axis =0)
        w1 = w1 - alpha * dcdw1
        w2 = w2 - alpha * dcdw2
        b1 = b1 - alpha * dcdb1
        b2 = b2 - alpha * dcdb2 
        a0 , z1 , a1 , z2, a2 = forward_prop(trainData[num_batch * batch: (num_batch+1)*batch,:])
        print('Training Accuracy : ',accuracy(a2,trainlabel,trainData.shape[0]))
        

NameError: name 'max_data' is not defined